// export const data = [
//   {
//     id: 1,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 24,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 2,
//     companyName: "Camson & Son’s Ventures",
//     email: "samuel.lambert@aol.com",
//     address: "993 Harvest Quail Hollow",
//     dateCreated: "01/29/2022",
//     noOfStaff: 4,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 3,
//     companyName: "Camson & Son’s Ventures",
//     email: "t.mcdonald@gmail.com",
//     address: "1034 Cozy Court",
//     dateCreated: "01/29/2022",
//     noOfStaff: 233,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 4,
//     companyName: "Camson & Son’s Ventures",
//     email: "m.snyder@msn.com",
//     address: "549 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 249,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 5,
//     companyName: "Camson & Son’s Ventures",
//     email: "wayne.franklin@live.com",
//     address: "583 Jagged Arbor",
//     dateCreated: "01/29/2022",
//     noOfStaff: 354,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 6,
//     companyName: "Camson & Son’s Ventures",
//     email: "c.griffith@outlook.com",
//     address: "703 Lost Round",
//     dateCreated: "01/29/2022",
//     noOfStaff: 3992,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 7,
//     companyName: "Camson & Son’s Ventures",
//     email: "t.lambert@verizon.net",
//     address: "743 Colonial Autumn Knoll",
//     dateCreated: "01/29/2022",
//     noOfStaff: 2834,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 8,
//     companyName: "Camson & Son’s Ventures",
//     email: "m.ferguson@yahoo.com",
//     address: "1234 Hidden Subdivision",
//     dateCreated: "02/29/2022",
//     noOfStaff: 6,
//     country: "Canada",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 9,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "846 Burning Terrace",
//     dateCreated: "03/22/2022",
//     noOfStaff: 9484,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 10,
//     companyName: "Camson & Son’s Ventures",
//     email: "t.morris@hotmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 938,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 11,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 32,
//     country: "Nigeria",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 12,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 544,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 13,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2021",
//     noOfStaff: 14,
//     country: "Ghana",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 14,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 93,
//     country: "United States of America",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 15,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 43,
//     country: "South Africa",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 16,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 54,
//     country: "France",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 17,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 43,
//     country: "South Africa",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 18,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 54,
//     country: "France",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 19,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 43,
//     country: "South Africa",
//     netWorth: "~ $24.3M",
//   },
//   {
//     id: 20,
//     companyName: "Camson & Son’s Ventures",
//     email: "craig.cohen@gmail.com",
//     address: "833 Dusty Orchard",
//     dateCreated: "01/29/2022",
//     noOfStaff: 54,
//     country: "France",
//     netWorth: "~ $24.3M",
//   },
// ];

export const COLUMNS = [
  {
    Header: "Company name",
    accessor: "company_name",
  },
  {
    Header: "Email",
    accessor: "email",
  },
  {
    Header: "Address",
    accessor: "address",
  },
  {
    Header: "Date Created",
    accessor: "createdAt",
  },
];
